[package]
name = "twim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"

[lints.clippy]
correctness = "deny"
suspicious = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"